version: 2.1
orbs:
  shiftleft: shiftleft/shiftleft@1.0
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: mvn package #if necessary, build app
      - shiftleft/analyze:
          app: YOUR_APP_NAME
          target: target/<PATH_TO_JAR_OR_WAR>
          language: java #app language
workflows:
  workflow:
    jobs:
      - build
