version: 2.1
orbs: 
  #shiftleft: shiftleft/shiftleft@1.0.6
jobs:
  build:
    machine: true
    steps:
    - run:
      - checkout
      - run: mvn package
        app: Shiftleft-Java-Demo-CircleCI
        target: target/hello-shiftleft-0.0.1.jar
        language: java
workflows:
  version: 2.1
  workflow:
    jobs:
      - build
